import crypto from 'node:crypto'

const API_BASE = 'https://www.signwell.com/api/v1'

// Coordinates for the signature/date/full-name overlay fields, in points,
// page 1, top-left origin. These must match the approvalBlock() in
// src/lib/pdfV2.js (ANCHOR_X/ANCHOR_Y and the signature-row layout inside
// it) — the PDF sent to SignWell is generated by that function, and these
// fields are placed on top of the dashed signature box / שם מלא / תאריך
// החתימה lines it draws. Measured directly (PyMuPDF) off rendered output at
// both a one-line and a full 300-char description (MAX_EXCEPTION_DESCRIPTION_LENGTH)
// to confirm the pinned block's position doesn't shift with content length —
// not yet confirmed against a real SignWell test send. SignWell's own
// coordinate origin (top-left vs PDF-native bottom-left) is unverified
// without live credentials; if fields land upside-down/mirrored on the first
// real test, flip y -> (841.89 - y - height) for each field.
export const SIGNWELL_FIELDS = {
  fullName: { page: 1, x: 290, y: 676, width: 199, height: 18 },
  signature: { page: 1, x: 368, y: 720, width: 184, height: 42 },
  dateSigned: { page: 1, x: 43, y: 676, width: 114, height: 18 },
}

function apiKey() {
  const key = process.env.SIGNWELL_API_KEY
  if (!key) throw new Error('SIGNWELL_API_KEY not configured')
  return key
}

export function isTestMode() {
  return process.env.SIGNWELL_TEST_MODE !== 'false'
}

async function signwellFetch(path, options) {
  const res = await fetch(`${API_BASE}${path}`, {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      'X-Api-Key': apiKey(),
      ...(options?.headers || {}),
    },
  })
  if (!res.ok) {
    const body = await res.text().catch(() => '')
    throw new Error(`SignWell ${path} failed: ${res.status} ${body}`)
  }
  return res.json()
}

// pdfBase64: raw base64 (no data: prefix). recipient: { name, email? }.
export async function createSignwellDocument({ pdfBase64, fileName, recipientName, recipientEmail }) {
  const recipientId = '1'
  const recipient = { id: recipientId, name: recipientName }
  if (recipientEmail) recipient.email = recipientEmail

  const body = {
    test_mode: isTestMode(),
    draft: false,
    embedded_signing: false,
    name: fileName,
    files: [{ file_base64: pdfBase64, name: fileName }],
    recipients: [recipient],
    fields: [
      [
        { ...SIGNWELL_FIELDS.signature, type: 'signature', recipient_id: recipientId, required: true, api_id: 'signature' },
        {
          ...SIGNWELL_FIELDS.dateSigned,
          type: 'autofill_date_signed',
          recipient_id: recipientId,
          required: true,
          api_id: 'date_signed',
        },
        { ...SIGNWELL_FIELDS.fullName, type: 'text', recipient_id: recipientId, required: true, api_id: 'full_name' },
      ],
    ],
  }

  return signwellFetch('/documents/', { method: 'POST', body: JSON.stringify(body) })
}

// url_only=false returns the raw PDF bytes directly (avoids a second
// round-trip to follow a file_url).
export async function fetchCompletedPdf(documentId) {
  const res = await fetch(`${API_BASE}/documents/${documentId}/completed_pdf?url_only=false`, {
    headers: { 'X-Api-Key': apiKey() },
  })
  if (!res.ok) {
    const body = await res.text().catch(() => '')
    throw new Error(`SignWell completed_pdf failed: ${res.status} ${body}`)
  }
  return Buffer.from(await res.arrayBuffer())
}

// https://developers.signwell.com/reference/event-hash-verification.md —
// HMAC-SHA256 of "{event_type}@{event_time}", keyed by the webhook's own id
// (SIGNWELL_WEBHOOK_ID, from the SignWell dashboard when the webhook was
// registered — not the API key).
export function verifyEventHash({ eventType, eventTime, hash }) {
  const webhookId = process.env.SIGNWELL_WEBHOOK_ID
  if (!webhookId) throw new Error('SIGNWELL_WEBHOOK_ID not configured')
  if (!eventType || !eventTime || !hash) return false
  const expected = crypto
    .createHmac('sha256', webhookId)
    .update(`${eventType}@${eventTime}`)
    .digest('hex')
  const a = Buffer.from(expected)
  const b = Buffer.from(String(hash))
  if (a.length !== b.length) return false
  return crypto.timingSafeEqual(a, b)
}
