import crypto from 'node:crypto'

const API_BASE = 'https://www.signwell.com/api/v1'

// Coordinates for the signature/date/full-name overlay fields, page 1,
// top-left origin. These must match the approvalBlock() in src/lib/pdfV2.js
// (ANCHOR_X/ANCHOR_Y and the signature-row layout inside it) — the PDF sent
// to SignWell is generated by that function, and these fields are placed on
// top of the dashed signature box / שם מלא / תאריך החתימה lines it draws.
//
// Confirmed via a real SignWell test send (2026-07-22): SignWell's own
// document viewer renders the page at 96 DPI (a 595.28pt-wide A4 page draws
// at 793 CSS px — the standard 96/72 pt-to-px ratio) but places API-supplied
// field x/y/width/height as raw, UNSCALED CSS pixels — i.e. it expects
// coordinates in 96-DPI pixels, not the 72-DPI PDF points pdfmake/PyMuPDF
// use. Values below are the PyMuPDF-measured PDF-point positions (see the
// git history of this file for those raw numbers) multiplied by 96/72
// (≈1.3333) to compensate. If SignWell ever fixes this on their end, these
// will need dividing back down by that same factor.
const PT_TO_SIGNWELL_PX = 96 / 72
const rawFieldsPt = {
  fullName: { x: 290, y: 676, width: 199, height: 18 },
  signature: { x: 368, y: 720, width: 184, height: 42 },
  dateSigned: { x: 43, y: 676, width: 114, height: 18 },
}
export const SIGNWELL_FIELDS = Object.fromEntries(
  Object.entries(rawFieldsPt).map(([name, f]) => [
    name,
    {
      page: 1,
      x: f.x * PT_TO_SIGNWELL_PX,
      y: f.y * PT_TO_SIGNWELL_PX,
      width: f.width * PT_TO_SIGNWELL_PX,
      height: f.height * PT_TO_SIGNWELL_PX,
    },
  ]),
)

function apiKey() {
  const key = process.env.SIGNWELL_API_KEY
  if (!key) throw new Error('SIGNWELL_API_KEY not configured')
  return key
}

export function isTestMode() {
  return process.env.SIGNWELL_TEST_MODE !== 'false'
}

async function signwellFetch(path, options) {
  const res = await fetch(`${API_BASE}${path}`, {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      'X-Api-Key': apiKey(),
      ...(options?.headers || {}),
    },
  })
  if (!res.ok) {
    const body = await res.text().catch(() => '')
    throw new Error(`SignWell ${path} failed: ${res.status} ${body}`)
  }
  return res.json()
}

// pdfBase64: raw base64 (no data: prefix). recipient: { name, email? }.
export async function createSignwellDocument({ pdfBase64, fileName, recipientName, recipientEmail }) {
  const recipientId = '1'
  const recipient = { id: recipientId, name: recipientName }
  if (recipientEmail) recipient.email = recipientEmail

  const body = {
    test_mode: isTestMode(),
    draft: false,
    embedded_signing: false,
    name: fileName,
    files: [{ file_base64: pdfBase64, name: fileName }],
    recipients: [recipient],
    fields: [
      [
        { ...SIGNWELL_FIELDS.signature, type: 'signature', recipient_id: recipientId, required: true, api_id: 'signature' },
        {
          ...SIGNWELL_FIELDS.dateSigned,
          type: 'autofill_date_signed',
          recipient_id: recipientId,
          required: true,
          api_id: 'date_signed',
        },
        { ...SIGNWELL_FIELDS.fullName, type: 'text', recipient_id: recipientId, required: true, api_id: 'full_name' },
      ],
    ],
  }

  return signwellFetch('/documents/', { method: 'POST', body: JSON.stringify(body) })
}

// url_only=false returns the raw PDF bytes directly (avoids a second
// round-trip to follow a file_url).
export async function fetchCompletedPdf(documentId) {
  const res = await fetch(`${API_BASE}/documents/${documentId}/completed_pdf?url_only=false`, {
    headers: { 'X-Api-Key': apiKey() },
  })
  if (!res.ok) {
    const body = await res.text().catch(() => '')
    throw new Error(`SignWell completed_pdf failed: ${res.status} ${body}`)
  }
  return Buffer.from(await res.arrayBuffer())
}

// https://developers.signwell.com/reference/event-hash-verification.md —
// HMAC-SHA256 of "{event_type}@{event_time}", keyed by the webhook's own id
// (SIGNWELL_WEBHOOK_ID, from the SignWell dashboard when the webhook was
// registered — not the API key).
export function verifyEventHash({ eventType, eventTime, hash }) {
  const webhookId = process.env.SIGNWELL_WEBHOOK_ID
  if (!webhookId) throw new Error('SIGNWELL_WEBHOOK_ID not configured')
  if (!eventType || !eventTime || !hash) return false
  const expected = crypto
    .createHmac('sha256', webhookId)
    .update(`${eventType}@${eventTime}`)
    .digest('hex')
  const a = Buffer.from(expected)
  const b = Buffer.from(String(hash))
  if (a.length !== b.length) return false
  return crypto.timingSafeEqual(a, b)
}
