// Prebuild: (1) generate src/lib/heeboFonts.js from @expo-google-fonts/heebo TTFs,
// (2) fetch staged source files from Supabase (deploy_files table) if missing locally.
// Both keep large files out of the deploy payload.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

// --- 1. Fonts ---
const pkg = join(root, 'node_modules', '@expo-google-fonts', 'heebo')
const regular = readFileSync(join(pkg, '400Regular', 'Heebo_400Regular.ttf')).toString('base64')
const bold = readFileSync(join(pkg, '700Bold', 'Heebo_700Bold.ttf')).toString('base64')
writeFileSync(
  join(root, 'src', 'lib', 'heeboFonts.js'),
  `// AUTO-GENERATED by scripts/gen-fonts.mjs — do not edit.\nexport const heeboRegular = "${regular}"\nexport const heeboBold = "${bold}"\n`,
)
console.log('heeboFonts.js generated')

// --- 2. Staged source files ---
const SUPABASE_URL = 'https://svsuntixvxwwuggtqsws.supabase.co'
const ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2c3VudGl4dnh3d3VnZ3Rxc3dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM2MDgxNzYsImV4cCI6MjA5OTE4NDE3Nn0.bV1HJ1dW4lQbqh3WnnqABaWFnot2_baKez0YqtwFwkU'

const res = await fetch(`${SUPABASE_URL}/rest/v1/deploy_files?select=path,content`, {
  headers: { apikey: ANON_KEY, Authorization: `Bearer ${ANON_KEY}` },
}).catch(() => null)

if (res?.ok) {
  const files = await res.json()
  for (const f of files) {
    const target = join(root, f.path)
    if (existsSync(target)) {
      console.log('exists, skipping:', f.path)
      continue
    }
    mkdirSync(dirname(target), { recursive: true })
    writeFileSync(target, f.content)
    console.log('fetched:', f.path, f.content.length, 'chars')
  }
} else {
  // Offline (local dev) — fine as long as the files already exist locally.
  const missing = ['src/pages/ManagerReport.jsx', 'src/pages/ManagerSettings.jsx'].filter(
    (p) => !existsSync(join(root, p)),
  )
  if (missing.length) {
    console.error('Cannot fetch staged files and they are missing locally:', missing)
    process.exit(1)
  }
  console.log('deploy_files fetch skipped (offline); local files present')
}
